version: '3.8'

services:
  # Banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: investimentos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: investimentos
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - investimentos-network

  # Backend Fastify
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: investimentos-backend
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: mysql://app_user:app_password_secure@db:3306/investimentos
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - investimentos-network

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: investimentos-frontend
    restart: always
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - investimentos-network

volumes:
  mysql_data:

networks:
  investimentos-network:
    driver: bridge
